name: Pull Request Preview

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code from the PR
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3️⃣ Install dependencies (force legacy peer deps)
      - name: Install dependencies (force legacy peer deps)
        run: npm install --legacy-peer-deps

      # 4️⃣ Run Webpack build (creates `dist/bundle.js`)
      - name: Build the project
        run: npm run build

      # 5️⃣ Debug: List contents of `dist/` folder after build
      - name: Debug: List contents of dist/
        run: |
          if [ -d dist ]; then
            echo "✅ dist directory exists"
            ls -la dist
          else
            echo "❌ dist directory is missing"
            exit 1
          fi

      # 6️⃣ Ensure `dist/` exists (create if missing)
      - name: Ensure dist directory exists
        run: mkdir -p dist

      # 7️⃣ Copy index.html from `src/` to `dist/` for GitHub Pages
      - name: Copy index.html to dist/
        run: cp src/index.html dist/index.html

      # 8️⃣ Debug: List contents of `dist/` folder after copying index.html
      - name: Debug: List contents of dist/ after copying index.html
        run: ls -la dist

      # 9️⃣ Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 🔟 Upload the build output (`dist/`) as an artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
          name: 'site-artifact'

      # 1️⃣1️⃣ Deploy the preview to GitHub Pages
      - name: Deploy to GitHub Pages (Preview Mode)
        uses: actions/deploy-pages@v3
        with:
          artifact_name: 'site-artifact'