name: Pull Request Preview

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the PR
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Install dependencies (Webpack v3.9.1)
      - name: Install dependencies
        run: npm install

      # 4. Run Webpack build (creates `dist/bundle.js`)
      - name: Build the project
        run: npm run build

      # 5. Copy index.html to dist/ for GitHub Pages
      - name: Copy index.html to dist/
        run: cp index.html dist/index.html

      # 6. Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 7. Upload the build output (`dist/`) as an artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
          name: 'site-artifact'

      # 8. Deploy the preview to GitHub Pages
      - name: Deploy to GitHub Pages (Preview Mode)
        uses: actions/deploy-pages@v3
        with:
          artifact_name: 'site-artifact'
          preview: true
