name: Pull Request Preview

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code from the PR
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3️⃣ Install dependencies (force legacy peer deps)
      - name: Install dependencies (legacy)
        run: npm install --legacy-peer-deps

      # 4️⃣ Run Webpack build (should create dist/bundle.js)
      - name: Build the project
        run: npm run build

      # 5️⃣ Debug: List contents of dist/ folder after build
      - name: Debug: List dist folder after build
        run: |
          echo "Listing dist folder after build:"
          ls -la dist || echo "No dist folder found!"

      # 6️⃣ Debug: Check if dist/bundle.js exists
      - name: Debug: Check for dist/bundle.js
        run: |
          if [ -f dist/bundle.js ]; then
            echo "✅ dist/bundle.js exists."
          else
            echo "❌ dist/bundle.js is missing!"
            exit 1
          fi

      # 7️⃣ Ensure the dist/ directory exists (create if missing)
      - name: Ensure dist directory exists
        run: mkdir -p dist

      # 8️⃣ Debug: Check if src/index.html exists
      - name: Debug: Check for src/index.html
        run: |
          if [ -f src/index.html ]; then
            echo "✅ src/index.html exists."
          else
            echo "❌ src/index.html is missing!"
            exit 1
          fi

      # 9️⃣ Copy index.html from src/ to dist/ for GitHub Pages
      - name: Copy index.html to dist/
        run: cp src/index.html dist/index.html

      # 🔟 Debug: List contents of dist/ folder after copying index.html
      - name: Debug: List dist folder after copying index.html
        run: |
          echo "Listing dist folder after copying index.html:"
          ls -la dist

      # 1️⃣1️⃣ Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 1️⃣2️⃣ Upload the build output (dist/) as an artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
          name: site-artifact

      # 1️⃣3️⃣ Deploy the preview to GitHub Pages
      - name: Deploy to GitHub Pages (Preview Mode)
        uses: actions/deploy-pages@v3
        with:
          artifact_name: site-artifact
