name: Pull Request Preview

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js (version 16)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Install dependencies (using legacy peer deps to avoid conflicts)
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Run the build (Webpack should output to the dist/ folder)
      - name: Build project
        run: npm run build

      # 5. Copy index.html from src/ to dist/ (so GitHub Pages can find it)
      - name: Copy index.html to dist/
        run: cp src/index.html dist/index.html

      # 6. Configure GitHub Pages (optional but recommended)
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 7. Set a unique deployment branch using the PR branch name
      - name: Set deployment branch name
        run: echo "DEPLOY_BRANCH=pr-preview/${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      # 8. Upload the built site (dist/) as an artifact with a unique name based on the branch
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
          name: github-pages-${GITHUB_HEAD_REF}

      # 9. Deploy the uploaded artifact to GitHub Pages by pushing it to the unique branch
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${GITHUB_HEAD_REF}
          branch: ${{ env.DEPLOY_BRANCH }}

      # 10. Write the unique deployment URL to the job summary for easy access
      - name: Write deployment URL to job summary
        run: |
          DEPLOY_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ env.DEPLOY_BRANCH }}/"
          echo "## Pages Preview Deployment" >> $GITHUB_STEP_SUMMARY
          echo "[View Deployment](${DEPLOY_URL})" >> $GITHUB_STEP_SUMMARY
