name: Pull Request Preview

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js (version 16)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Install dependencies using legacy peer deps to avoid conflicts
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Run the build (Webpack should output to the dist/ folder)
      - name: Build project
        run: npm run build

      # 5. Copy index.html from src/ to dist/ (so GitHub Pages can find it)
      - name: Copy index.html to dist/
        run: cp src/index.html dist/index.html

      # 6. Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 7. Create a unique artifact name based on branch
      - name: Set unique artifact name
        run: echo "ARTIFACT_NAME=github-pages-${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      # 8. Upload the built site (dist/) as a branch-specific artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
          name: ${{ env.ARTIFACT_NAME }}

      # 9. Deploy the uploaded artifact to GitHub Pages (Preview Mode) with a unique identifier
      - name: Deploy to GitHub Pages (Preview)
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ env.ARTIFACT_NAME }}
          preview: true

      # 10. Write the unique deployment URL to the job summary
      - name: Write deployment URL to job summary
        run: |
          echo "## Pages Preview Deployment" >> $GITHUB_STEP_SUMMARY
          echo "[View Deployment](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-preview/${{ github.head_ref }}/)" >> $GITHUB_STEP_SUMMARY