name: Pull Request Preview

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js (version 16)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Install dependencies using legacy peer deps to avoid conflicts
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Run the build (Webpack should output to the dist/ folder)
      - name: Build project
        run: npm run build

      # 5. Copy index.html from src/ to dist/ (so GitHub Pages can find it)
      - name: Copy index.html to dist/
        run: cp src/index.html dist/index.html

      # 6. Prepare branch-specific deployment folder by copying the build output into pr-preview/<branch>
      - name: Prepare deployment folder
        run: |
          mkdir -p pr-preview/${{ github.head_ref }}
          cp -r dist/* pr-preview/${{ github.head_ref }}/

      # 7. Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 8. Upload the branch-specific deployment folder as an artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pr-preview/${{ github.head_ref }}
          name: github-pages-${{ github.head_ref }}

      # 9. Deploy the uploaded artifact to GitHub Pages (Preview Mode)
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${{ github.head_ref }}
          preview: true

      # 10. Write the unique deployment URL to the job summary for easy access
      - name: Write deployment URL to job summary
        run: |
          DEPLOY_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-preview/${{ github.head_ref }}/"
          echo "## Pages Preview Deployment" >> $GITHUB_STEP_SUMMARY
          echo "[View Deployment](${DEPLOY_URL})" >> $GITHUB_STEP_SUMMARY
