name: Pull Request Preview

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: write

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js (version 16)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Install dependencies (using legacy peer deps to avoid conflicts)
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Run the build (Webpack should output to the dist/ folder)
      - name: Build project
        run: npm run build

      # 5. Copy index.html from src/ to dist/ (so GitHub Pages can serve it)
      - name: Copy index.html to dist/
        run: cp src/index.html dist/index.html

      # 6. Deploy to GitHub Pages using JamesIves/github-pages-deploy-action
      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages          # the branch where Pages is served from
          folder: dist              # the local folder to deploy
          target_folder: pr-preview/${{ github.head_ref }}  # deploy into a subfolder unique to this branch
          clean: false              # do not delete other preview folders

      # 7. Write the unique deployment URL to the job summary for easy access
      - name: Write deployment URL to job summary
        run: |
          DEPLOY_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-preview/${{ github.head_ref }}/"
          echo "## Pages Preview Deployment" >> $GITHUB_STEP_SUMMARY
          echo "[View Deployment](${DEPLOY_URL})" >> $GITHUB_STEP_SUMMARY
