name: Pull Request Preview

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    env:
      # For PR events, github.head_ref is set.
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      # 1. Checkout the repository.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js (version 16).
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Install dependencies (using legacy peer deps to avoid conflicts).
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Run the build (your bundler should output to the dist/ folder).
      - name: Build project
        run: npm run build

      # 5. Copy index.html (or other necessary files) so Pages can find it.
      - name: Copy index.html to dist/
        run: cp src/index.html dist/index.html

      # 6. Prepare a folder named after the branch inside a temporary builds/ directory.
      - name: Prepare branch build directory
        run: |
          mkdir -p builds/${BRANCH_NAME}
          cp -R dist/* builds/${BRANCH_NAME}/

      # 7. Deploy the builds/ folder to GitHub Pages incrementally.
      #    Because keep_files is true, the action updates only files present in builds/
      #    while leaving other folders (for other branches) untouched.
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: builds
          keep_files: true

      # 8. Write a summary with a link to the branch-specific preview.
      - name: Write deployment URL to job summary
        run: |
          echo "## Pages Preview Deployment \`${BRANCH_NAME}\`" >> $GITHUB_STEP_SUMMARY
          echo "[View Deployment](https://rebumatadele.github.io/poc-github-pages-v3/${BRANCH_NAME})" >> $GITHUB_STEP_SUMMARY
