name: Pull Request Preview

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code from the PR
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3️⃣ Install dependencies (force legacy peer deps)
      - name: Install dependencies (force legacy peer deps)
        run: npm install --legacy-peer-deps

      # 4️⃣ Run Webpack build (creates `dist/bundle.js`)
      - name: Build the project
        run: npm run build

      # 5️⃣ Ensure dist/ directory exists
      - name: Ensure dist directory exists
        run: mkdir -p dist

      # 6️⃣ Copy index.html from `src/` to `dist/` for GitHub Pages
      - name: Copy index.html to dist/
        run: cp src/index.html dist/index.html

      # 7️⃣ Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 8️⃣ Upload the build output (`dist/`) as an artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
          name: 'site-artifact'

      # 9️⃣ Deploy the preview to GitHub Pages
      - name: Deploy to GitHub Pages (Preview Mode)
        uses: actions/deploy-pages@v3
        with:
          artifact_name: 'site-artifact'
          preview: true
