name: Pull Request Preview

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-preview:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code from the PR
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3️⃣ Install dependencies (force legacy peer deps)
      - name: Install dependencies (force legacy peer deps)
        run: npm install --legacy-peer-deps

      # 4️⃣ Run Webpack build (creates `dist/bundle.js`)
      - name: Build the project
        run: npm run build

      # 5️⃣ Debug: Check if `dist/` exists before uploading
      - name: Debug: Check dist folder
        run: |
          if [ -d dist ]; then
            echo "✅ dist directory exists"
            ls -la dist
          else
            echo "❌ dist directory is missing"
            exit 1
          fi

      # 6️⃣ Ensure `dist/` exists before uploading
      - name: Ensure dist directory exists
        run: mkdir -p dist

      # 7️⃣ Copy index.html from `src/` to `dist/` for GitHub Pages
      - name: Copy index.html to dist/
        run: cp src/index.html dist/index.html

      # 8️⃣ Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      # 9️⃣ Upload the build output (`dist/`) as an artifact
      - name: Upload Pages Artifact
        run: |
          if [ -d dist ]; then
            echo "✅ Uploading dist folder..."
          else
            echo "❌ dist folder not found. Cannot upload!"
            exit 1
          fi
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'
          name: 'site-artifact'

      # 🔟 Deploy the preview to GitHub Pages
      - name: Deploy to GitHub Pages (Preview Mode)
        uses: actions/deploy-pages@v3
        with:
          artifact_name: 'site-artifact'
