name: Pull Request Preview

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
  push:
    branches:
      - '*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    env:
      # For pull requests, github.head_ref is set; fallback to github.ref_name otherwise.
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      # 1. Checkout the repository.
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js (version 16).
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Install dependencies (using legacy peer deps to avoid conflicts).
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # 4. Build project (make sure your build script outputs to "dist").
      - name: Build project
        run: npm run build

      # 5. (Optional) Copy additional files so GitHub Pages can find them.
      - name: Copy index.html to dist/
        run: cp src/index.html dist/index.html

      # 6. Debug: List the contents of the build output directory.
      - name: List build artifacts
        run: ls -alR dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          destination_dir: ${{ env.BRANCH_NAME }}
          exclude_assets: '.github'
          allow_empty_commit: true
          keep_files: true
          disable_nojekyll: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: "Deploy preview for branch '${{ env.BRANCH_NAME }}' (${GITHUB_SHA})"

      # 8. Write a job summary with the deployment URL.
      - name: Write deployment URL to job summary
        run: |
          echo "## Pages Preview Deployment \`${{ env.BRANCH_NAME }}\`" >> $GITHUB_STEP_SUMMARY
          echo "[View Deployment](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ env.BRANCH_NAME }}/)" >> $GITHUB_STEP_SUMMARY
